{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "waldur-site-agent-proxmox.fullname" . }}
  labels:
    {{- include "waldur-site-agent-proxmox.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.secretKey }}: |
    {{- required "config.content is required when config.existingSecret is empty" .Values.config.content | nindent 4 }}
{{- end }}

